version: 2

jobs:
  build:
    docker:
      - image: circleci/node:13.3.0
    steps:
      - checkout
      - run: npm install
  check-package:
    docker:
      - image: circleci/node:13.3.0
    steps:
      - checkout
      - run: npm run test

workflows:
  version: 2
  main:
    jobs:
      - build
      - check-package